# area_of_circle = 78.5

In [2]:
print("Area of the circle is - " + area_of_circle)

TypeError: must be str, not float

In [3]:
area_of_circle = str(area_of_circle)

In [4]:
area_of_circle_msg = "Area of the circle is - " + area_of_circle
print(area_of_circle_msg)

Area of the circle is - 78.5


In [3]:
try:
    pay = float(input("Hours:")) * float(input("Pay:"))
    print(pay)
except:
    print("Wrong input")

Hours:90
Pay:&90
Wrong input


In [ ]:
while True:
    line = input('> ')
    if line[0] == '#' :
        continue
    if line == 'done' :
        break
    print(line) 
print("done!")    

> #divi
> divi
divi
> you
you
> 123
123
> #234
> done


In [12]:
x=['apple','grapes','Banana','Apple','bab']
print(sorted(x))
print(x)
print(x.sort())
print(x)

['Apple', 'Banana', 'apple', 'bab', 'grapes']
['apple', 'grapes', 'Banana', 'Apple', 'bab']
None
['Apple', 'Banana', 'apple', 'bab', 'grapes']


In [49]:
x=',Monty Python '
print(x[0:2])

,M


In [30]:
import sys
for i in range(0,len(x)):
    sys.stdout.write(x[i]) #in single line

#Monty Python 

In [39]:
sorted(x)

[' ', ' ', '#', 'M', 'P', 'h', 'n', 'n', 'o', 'o', 't', 't', 'y', 'y']

In [31]:
'on' in x

True

In [40]:
x.strip() #remove wspace

'#Monty Python'

In [43]:
x.replace('#','*')

',Monty Python '

In [45]:
x.split(",")

['', 'Monty Python ']

In [52]:
x.join('hey')

'h,Monty Python e,Monty Python y'

In [53]:
x.capitalize() #only first character is capitalized

',monty python '

In [55]:
word = 'geeks for geeks'
print(word.find('geeks', 2))   #find(substr,start,end)

10


In [14]:
ord('B')

66

In [2]:
def print_even(n):
    for i in range(0,n):
        if(i%2==0):
            print(i)
        i=i+1           

In [5]:
print_even(0)

In [2]:
def compound_interest(principle,rate,years):
    n_p = principle
    for i in range(1,years+1):
        s_i = (n_p*rate*1)/100
        n_p = s_i + n_p
        i = i+1
    comp_interest = n_p-principle
    return comp_interest        

In [3]:
compound_interest(100,5,2)

10.25

In [49]:
x = [9,41,13,45,67]
type(x)

list

In [50]:
L = x.extend(x)
print(L)
x

None


[9, 41, 13, 45, 67, 9, 41, 13, 45, 67]

In [51]:
x.index(41,2,9) #(value,start,end)

6

In [52]:
x.pop(x.index(41))
x

[9, 13, 45, 67, 9, 41, 13, 45, 67]

In [53]:
x.reverse()
x

[67, 45, 13, 41, 9, 67, 45, 13, 9]

In [62]:
print(sorted(x))
print(x.sort())  #changes the org seq; returns none

[9, 9, 13, 13, 41, 45, 45, 67, 67]
None


In [65]:
help(x)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [69]:
counts = {}
names = ['divi','navi','hari','navi','divi','navi']
for name in names:
    if name not in counts:
        counts[name] = 1
    else:
        counts[name]=counts[name]+1
print(counts)        

{'divi': 2, 'navi': 3, 'hari': 1}


In [70]:
L=list()
for name in names:
    L.append(names.count(name))
print(max(L))

3


In [1]:
counts = {}
names = ['divi','navi','hari','navi','divi','navi']
for name in names:
    counts[name] = counts.get(name,0) + 1
print(counts)    

{'divi': 2, 'navi': 3, 'hari': 1}


In [3]:
counts = dict()     #counting the words in line/file
line = input('Enter a line of text: ')
words = line.split()
print('counting...')
for word in words:
    counts[word] = counts.get(word,0) + 1
print(counts)    

Enter a line of text: i was laughing i kicked him and punched
counting...
{'i': 2, 'was': 1, 'laughing': 1, 'kicked': 1, 'him': 1, 'and': 1, 'punched': 1}


In [5]:
jjj = {'chuck':1,'fred':3,'jan':5}
print(list(jjj))
print(jjj.keys())
print(jjj.values())
print(jjj.items())

['chuck', 'fred', 'jan']
dict_keys(['chuck', 'fred', 'jan'])
dict_values([1, 3, 5])
dict_items([('chuck', 1), ('fred', 3), ('jan', 5)])


In [6]:
for name,val in jjj.items():
    print(name,val)

chuck 1
fred 3
jan 5


In [ ]:
name = input('Enter file: ')
handle = open(name)
text = handle.read()
words = text.split()

counts=dict()
for word in words:
    counts[word]=counts.get(word,0)+1
    
bigword=None
bigcount=None
for word,count in counts.items():
    if bigword is None or count>bigcount:
        bigword=word
        bigcount=count
        
print(bigword,bigcount)        

In [15]:
counts = dict()     #counting the words in line/file
line = input('Enter a line of text: ')
words = line.split()

for word in words:
    counts[word] = counts.get(word,0) + 1
L=list()
for (word,val) in counts.items():
    L.append((val,word))
    
L.sort(reverse = True)

for (val,word) in L[:5]:
    print(word, val)

Enter a line of text: Coding Ninjas lay a great foundation for any student. The way I used to solve problems before joining coding ninjas and after made a lot of difference. Topics like Recursion , DP , Hashing etc which seemed to be tricky and difficult seems no more difficult after the in-depth knowledge and practice assignments provided by coding ninjas. Last but not the least I learned how to find a solution rather than knowing or mugging a solution from Ankush sir , he made problems look so easy.
a 4
to 3
and 3
, 3
the 2


In [36]:
c={'a':10, 'b':23, 'c':14}  #list comprehension
print(sorted(  (v,k) for (k,v) in c.items()  ))

[(10, 'a'), (14, 'c'), (23, 'b')]


In [20]:
l = dict()
l['1'] = 'one'
l['2'] = 'two'
print(l)
l['3'] = 'three'
print(l)

{'1': 'one', '2': 'two'}
{'1': 'one', '2': 'two', '3': 'three'}


In [27]:
L = [('one',1),('two',2)]
print(dict(L))
a=list((1,2))   #tuple to list
print(a)
b=tuple([1,2])  #list to tuple
print(b)

{'one': 1, 'two': 2}
[1, 2]
(1, 2)


In [32]:
#x=(1)
#type(x)
y=(1,)
type(y)
x = (1,)+(2,)+(3,4)
x

(1, 2, 3, 4)

In [36]:
import re
#. means any sngle character
# * means
#re.findall("t..", "this is a aa and that is a aaa")
print(re.findall("a+", "this is a aa and that is a aaa"))  #one or more occurences of prev subexp(here is 'a')
print(re.findall(".*", "this is a aa and that is a aaa"))  #zero or more occurences of prev.
# '.*' prints whole line
# '//+' for searching +
#print(re.findall(".\\+", "th+is is a aa and that is a aaa"))
#print(re.findall("^t", "this is a aa and that is a aaa")) #beginning of line
#print(re.findall(".$", "this is a aa and that is a aaa"))  #ending of line
#print(re.findall("a\S", "this is a aa and that is a aaa"))  #'\S' is for non-white space
#print(re.findall("a?", "this is a aa and that is a aaa"))
print(re.findall("[0-9]+", "this 3 is 4a aa and that is a aaa"))

['this is a aa and that is a aaa']
['this is a aa and that is a aaa', '']
['3', '4']


In [39]:
x = 'From divnoorsingh675@gmail.com Sat Jan 09:14:16 2020'
y = re.findall('\S+@\S+',x)
print(y)

['divnoorsingh675@gmail.com']


In [40]:
x = 'From: Using the : character'
y = re.findall('^F.+:',x)
print(y)

['From: Using the :']


In [42]:
x = 'From: Using the : character'
#y = re.findall('^F[^ ]+:',x)
y = re.findall('^F.+?:',x) #non greedy
print(y)

['From:']


In [1]:
'{:>10}'.format('test')

'      test'

In [14]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic1.update(dic2)
print(dic1)

{1: 10, 2: 20, 3: 30, 4: 40}


In [1]:
L = dict()
for key in range(1,16):
    L[key] = (key*key)
print(L)    

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [4]:
key1 = int(input("Enter key: "))
if(key1 in list(L)):
    print("Key is present!")
else:
    print("Key is not present!")

Enter key: 16
Key is not present!


In [10]:
word = str(input("Enter string: "))
L =dict()
for char in word:
    L[char] = L.get(char,0)+1
print(L)

Enter string: geeks for geeks
{'g': 2, 'e': 4, 'k': 2, 's': 2, ' ': 2, 'f': 1, 'o': 1, 'r': 1}


In [15]:
dic3 = {'Math':81, 'Physics':83, 'Chemistry':87}
print( sorted( ((v,k) for (k,v) in dic3.items()), reverse = True))


[(87, 'Chemistry'), (83, 'Physics'), (81, 'Math')]


In [12]:
class PartyAnimal:
    x = 0
    name = ""
    def __init__(self,nam):   #all functions of class must have 'self'  
        self.name = nam
        print(self.name,"constructed")
        
    def party(self):
        self.x = self.x +1
        print(self.name,"party count", self.x)
        
class Football(PartyAnimal):
    points = 0
    def touchdown(self):
        self.points = self.points + 1
        self.party()
        print(self.name,"points",self.points)
        
an = PartyAnimal("Sally")   
an.party()
an.party()

j = Football("Jim")
j.party()
j.touchdown()

Sally constructed
Sally party count 1
Sally party count 2
Jim constructed
Jim party count 1
Jim party count 2
Jim points 1


In [13]:
import os
print(os.listdir())

['cat_vs_noncat_classifier.ipynb', 'classify_clothes.ipynb', 'Bikes_problem.ipynb', '.ipynb_checkpoints', 'Bikes_solution.ipynb', 'Untitled.ipynb', 'Python.ipynb', 'End_to_end_project.ipynb', '.ipynb', 'scala_spark.ipynb']


In [19]:
sent = '0123456789'
print(sent[-1::-1])
#print(sent[8::1])

9876543210


In [7]:
message = 'I love NeuralNine!'
message = [x.upper for x in message if x in "aeiou"]
print(message)

[<built-in method upper of str object at 0x7fe1502d9030>, <built-in method upper of str object at 0x7fe150325180>, <built-in method upper of str object at 0x7fe150325180>, <built-in method upper of str object at 0x7fe150366d18>, <built-in method upper of str object at 0x7fe1502d1260>, <built-in method upper of str object at 0x7fe150307f10>, <built-in method upper of str object at 0x7fe150325180>]


In [6]:
message = sorted(message, reverse= True)
print(message)

TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'builtin_function_or_method'

In [ ]:
25

In [1]:
25*4

100

In [3]:
(7 + 6 + 0 + 4 + 3) // 5

4

In [4]:
(5000*10*4)/100

2000.0

In [1]:
bank_balance =200
print(bank_balance )

200


In [5]:
height = 60
width = 40
new_area_of_rectangle= height * width
print(new_area_of_rectangle)

2400


In [65]:
def file_read_func(path):
    try:
        with open(path) as f:
            content = f.read()
            content = content.replace('\n',' ')
            list_of_words = content.split(" ")
            sum = 0
            for word in list_of_words:
                sum = sum + len(word)
            return sum    
    except:
        return -1

In [66]:
file_read_func("/home/divnoorsingh6758219/cloudxlab_jupyter_notebooks/test12")

28

# numpy n pandas

In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x.shape

(3, 4)

In [7]:
np.full((3,4),0.11)

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [8]:
np.arange(10,30,6)

array([10, 16, 22, 28])

In [9]:
np.linspace(0,100,10)  #prints evenly distributed no.s b/w two extremes(10 no.s b/w 0-100)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [10]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [12]:
b= a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [13]:
a=np.array([1,2,4,6,9,12])
a_slice=a[1:5]
a_slice[1]=1000
print(a)

[   1    2 1000    6    9   12]


In [16]:
b = np.array([True, False, True])
b

array([ True, False,  True])

In [17]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
a[b]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [20]:
a=np.array([10,20,30,40])
b=np.arange(4)
c=a+b
c

array([10, 21, 32, 43])

In [22]:
A = np.array([[1,1],
            [0,1]])   #element wise product
B= np.array([[2,0],
            [3,4]])

print(A*B)

[[2 0]
 [0 4]]


In [23]:
print(np.dot(A,B))   #matrix mul

[[5 4]
 [3 4]]


In [30]:
list = [1,2,3]

In [31]:
list_array = np.array(list)
print(list_array)

[1 2 3]


In [32]:
tup = (1,2,3)

In [34]:
my_tup_array = np.array(tup)
print(my_tup_array)

[1 2 3]


In [40]:
def multiply_loops(A,B):
    c = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[1]):
        for j in range(B.shape[0]):
            c[i,j] = A[i,j] * B[j,i]
    return c

In [41]:
def multiply_vector(A, B):
     return A @ B

In [42]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

4.63 ms ± 48.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.7 µs ± 752 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [47]:
tup_dim = (3, 4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [48]:
my_ones_array = np.ones( tup_dim, dtype=np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [49]:
my_seven_array = np.full( tup_dim, 7, dtype=np.int16)
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [50]:
my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [75]:
my_rand_array = np.random.rand(3,4)
print(my_rand_array)

[[0.50110066 0.97983825 0.47263034 0.29603048]
 [0.04035984 0.25022378 0.11973324 0.82976204]
 [0.42689147 0.08554431 0.07036895 0.94391827]]


In [76]:
tup_dim = (3, 4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[0.50110066 0.97983825 0.47263034 0.29603048]
 [0.04035984 0.25022378 0.11973324 0.82976204]
 [0.42689147 0.08554431 0.07036895 0.94391827]]


In [85]:
my_range_array = np.arange(10,30,5)
print(my_range_array)

[10 15 20 25]


In [87]:
my_spaced_array = np.linspace(0,5/3,6)
print(my_spaced_array)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [4]:
my_array  = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [13]:
#Two ways (constructs) in NumPy to load data from a text file:
#(1) using loadtxt() function
#(2) using genfromtxt() function

import os
import pandas as pd
HOUSING_PATH = '../ml/machine_learning/datasets/housing/'
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))


In [14]:
my_df = housing_raw.iloc[ : 5]
my_df.to_csv('housing_short.csv', index=False)

In [22]:
#FILE = 'housing_short.csv'
#def load_housing_data(file = FILE ):
 #   return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [31]:
#longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [32]:
#print(median_house_value_arr )

[452600. 358500. 352100. 341300. 342200.]


In [50]:
FILE = os.path.join(HOUSING_PATH, "housing.csv")

In [51]:
def load_housing_dataset(file =FILE ):
    return np.genfromtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skip_header=1, filling_values = 99999999, unpack=False)

In [52]:
result_arr = load_housing_dataset()

In [53]:
print(len(result_arr))
print(result_arr)

20640
[(-122.23, 37.88, 41.,  880.,  129.,  322.,  126., 8.3252, 452600., b'NEAR BAY')
 (-122.22, 37.86, 21., 7099., 1106., 2401., 1138., 8.3014, 358500., b'NEAR BAY')
 (-122.24, 37.85, 52., 1467.,  190.,  496.,  177., 7.2574, 352100., b'NEAR BAY')
 ...
 (-121.22, 39.43, 17., 2254.,  485., 1007.,  433., 1.7   ,  92300., b'INLAND')
 (-121.32, 39.43, 18., 1860.,  409.,  741.,  349., 1.8672,  84700., b'INLAND')
 (-121.24, 39.37, 16., 2785.,  616., 1387.,  530., 2.3886,  89400., b'INLAND')]


In [59]:
my_arr= np.array([[1,2,3,4],
                 [5,6,7,8]])

In [61]:
my_arr.resize((3,4))
print(my_arr)

[[1 2 3 4]
 [5 6 7 8]
 [0 0 0 0]]


In [66]:
my_first_arr = np.array([1,2,3,4,5,6,7,8])

In [67]:
my_new_arr =  my_first_arr.reshape(2,4)  #reshape() creates new array of same size only 
print(my_new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [68]:
print(my_first_arr)

[1 2 3 4 5 6 7 8]


In [69]:
my_second_arr = np.array([0,1,2,3,4,5,6,7,8])
my_updated_arr = my_second_arr.reshape(-1,3)   #if rows are unknown replace it wid -1
print(my_updated_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
print(my_second_arr)

[0 1 2 3 4 5 6 7 8]


In [80]:
my_orig_arr = np.array([1,15,3,9,26,7,89,12])
my_rev_arr = my_orig_arr[::-1]
print(my_rev_arr)

[12 89  7 26  9  3 15  1]


In [86]:
apple =np.array([1,8,23,3,18,91,7,15])
apple_slice = apple[1:4]
print(apple_slice)
print(apple)

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]


In [84]:
apple_slice[1]=99999
print(apple_slice)
print(apple)

[    8 99999     3]
[    1     8 99999     3    18    91     7    15]


In [87]:
apple_slice_new = apple[2 : 5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[    23 222222     18]
[ 1  8 23  3 18 91  7 15]


In [99]:
from sklearn.datasets import load_sample_image

In [100]:
china = load_sample_image("china.jpg")

In [101]:
#portion = china[120:250, 110:230]
#print(portion.shape)

(130, 120, 3)


In [106]:
china.shape

(427, 640, 3)

In [107]:
image = china[150:220, 130:250]
image.shape

(70, 120, 3)

In [108]:
height, width, channels = image.shape

In [110]:
image_grayscale = image.mean(axis=2).astype(np.float32)
image_grayscale.shape

(70, 120)

In [119]:
images = image_grayscale.reshape(1, height, width, 1)
#images.shape
print(images.ndim)

4


In [126]:
my_multi_arr=np.arange(20).reshape(4,5)
my_multi_arr_portion = my_multi_arr[2:4,2:5]
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [133]:
my_2d_arr = np.arange(20).reshape(4,5)
my_1d_arr = my_2d_arr.ravel() #converts 2-d,3-D into 1-D
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [140]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)
c_arr = a_arr+b_arr
print(c_arr)

[60 71 82 93]


In [191]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)
f_arr = d_arr - e_arr
print(f_arr)

[60 69 78 87]


In [208]:
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr = A_arr * B_arr
print(M_arr)

[[10 72]
 [ 4 42]]


In [209]:
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr,D_arr)
print(P_arr)

[[19 94]
 [15 74]]


In [226]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array( [ [2, 10], [4, 5] ] )
T_div = R_div/S_div
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [227]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array( [ [2, 10], [8, 3] ] )
T_int_div = R_int_div//S_int_div
print(T_int_div)

[[12  6]
 [ 5 23]]


In [228]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array( [ [2, 10], [8, 3] ] )
T_mod = R_mod%S_mod
print(T_mod)

[[0 5]
 [0 1]]


In [247]:
R_exp= np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )
T_exp = R_exp ** S_exp
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [256]:
U = np.array([ [ 22, 45], [90, 4 ] ] )
print(U[U<45])     #elements less than 45

[22  4]


In [262]:
X_stat = np.array( [ [ 1, 2, 3], [ 4, -5, 6] ])
print("mean = ",X_stat.mean())
print("Variance = ", X_stat.var())
print("Standard Deviation = ", X_stat.std())
print("min = ", X_stat.min())
print("max = ", X_stat.max())
print("sum = ", X_stat.sum())
print("product = ", X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
min =  -5
max =  6
sum =  11
product =  -720


In [274]:
Z = np.arange(18).reshape(2,3,3)
print(Z)    

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [275]:
print(Z.sum(axis=2))

[[ 3 12 21]
 [30 39 48]]


In [282]:
N = np.arange(6).reshape(3,2)
print(N)

[[0 1]
 [2 3]
 [4 5]]


In [283]:
print("Transpose = ", N.T)

Transpose =  [[0 2 4]
 [1 3 5]]


In [289]:
X_broad = np.ones((3,3))
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [290]:
Y_broad = np.arange(3)
print(Y_broad)

[0 1 2]


In [291]:
Z_broad = X_broad + Y_broad
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
